### ISSUE TITLE
Exception when initializing Rollbar service

### ISSUE THREAD

**Issue by azuken** [rollbar/Rollbar.NET#475] opened 2019-11-18 16:13 UTC
**Describe the bug**
An exception is occuring when launching Xamarin forms app, and initializing rollbar.
`System.MissingMethodException "Method not found: string SQLitePCL.raw.sqlite3_db_filename(SQLitePCL.sqlite3,string)"`

**To Reproduce**
1. Initialize configuration with Person, payload and environment
2. Launch app

**Expected behavior**
Rollbar service correctly initialized

**Screenshots**

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: Mobile app
 - OS and its version: Android 10 & iOS 13
 - .NET flavor and its version: .NET Standard 2.1
 - Application framework and its version: Xamarin
 - Rollbar.NET Version: 3.6.2
 - Applicable Rollbar Plug-in (if any): None
 - Applicable custom third party logging library/framework integration (if any): None
 - Applicable Browser (if any): None

**Additional context**``
None

**Comment by akornich** [comment] 2019-11-18 18:43
Hi, @azuken. Thanks for reporting the issue. May I ask you to try building/running this [sample app we have for using Rollbar.NET with Xamarin](https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.Xamarin.Forms.sln)? Can you repro the problem with the sample app?

**Comment by azuken** [comment] 2019-11-19 09:35
I've tried your sample app. It launches fine, but with an exception at startup : 

```
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
  at System.Configuration.ClientConfigPaths..ctor (System.String exePath, System.Boolean includeUserConfig) [0x00050] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigPaths.GetPaths (System.String exePath, System.Boolean includeUserConfig) [0x00018] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.get_ConfigPaths () [0x0000a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.GetStreamName (System.String configPath) [0x0006d] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.get_IsAppConfigHttp () [0x00000] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.Internal.DelegatingConfigHost.get_IsAppConfigHttp () [0x00006] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationSystem..ctor () [0x00051] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ConfigurationManager.EnsureConfigurationSystem () [0x00024] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
   --- End of inner exception stack trace ---
  at System.Configuration.ConfigurationManager.PrepareConfigSystem () [0x0001a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ConfigurationManager.GetSection (System.String sectionName) [0x0000a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at Rollbar.NetFramework.RollbarConfigSection.GetConfiguration () [0x00002] in /xxxxxxxx/Rollbar.NET-master/Rollbar/NetFramework/RollbarConfigSection.cs:27 
```

(This exception shows up several times)

But app seems to work fine.

On Visual Studio For Mac, I cannot go to Rollbar project, it fails to load (target framework issue ? )

**Comment by akornich** [comment] 2019-11-19 18:30
@azuken , thank you very much for following it up! I'll look into the exception.
Yes, it is expected that the SDK codebase can not be worked on from VS for Mac since the codebase/SDK targets .NET flavors that are not supported by VS for Mac (like original/not-Core  .NET Framework). The development of this SDK needs to be done with VS on Windows. 
Now, going back to the initial problem that you reported: I assume the way you integrated the SDK into your own app is very similar to the way it is done in our sample app with the main difference that you are integrating the SDK via a Nuget package. Correct?

**Comment by akornich** [comment] 2019-11-19 20:41
@azuken , i was trying to repro the `System.PlatformNotSupportedException` within our sample app using iphone 8 ios13.2 simulator  (VS2019 on Windows) without luck. What was your test configuration?

**Comment by akornich** [comment] 2019-11-19 21:22
Ok, got the `System.PlatformNotSupportedException` repro on the Android platform.  It is not an unhandled exception. We already "expected" it and handled by just tracing the error. Once the .Net Core actually implements config section reading API, the exception will not be generated at all.
So, I am switching back to looking into the sqlite related exception. I hope I can repro it somehow...

**Comment by akornich** [comment] 2019-11-20 06:36
@azuken , i created a similar xamarin mobile app project on VS for Mac and integrated the Rollbar.NET 3.6.2 via Nuget. It runs fine on both iOS and Android simulators. No `System.MissingMethodException` and the payloads making their way to the Rollbar Dashboard. 
I'll add this sample to our repo tomorrow.

**Comment by azuken** [comment] 2019-11-20 10:12
@akornich It's understood for the SDK codebase on Mac.
After rechecking your Xamarin.Forms sample, we initialize Rollbar config like you.

Here is our code : 

(We have a shared interface in our Forms project, which is implemented in each platform project)

Android & iOS :

```
private static RollbarConfig _config;
string username = "test";
string environment = "test_env";
_config = new RollbarConfig("TOKEN");
_config.Transform = payload =>
            {
                payload.Data.Platform = Device.RuntimePlatform;
            };

var id = string.IsNullOrEmpty(username) ? "0" : username.SubString(40);
_config.Person = new Person(id)
            {
                UserName = username
            };
_config.Environment = string.IsNullOrWhiteSpace(environment) ? "debug" : environment;
RollbarLocator.RollbarInstance
                          .Configure(_config);
```

I didn't reproduced `System.PlatformNotSupportedException`too on iOS, with your sample project.
It only show on Android, as you said.

After clean my solution, and retry, same SQLlite3 issue happen. We have `Akavache` nuget package which use SQLlite3 too, maybe a dependency conflict, with netstandard implicit dependencies ?

**Comment by akornich** [comment] 2019-11-20 22:30
@azuken , thanks for the feedback. I am not familiar with Akavache but will try to look into it and maybe play with it today...

**Comment by akornich** [comment] 2019-11-21 04:46
@azuken , may i ask you to try this experimental nuget package that is attached here?
[Rollbar.3.6.3.nupkg.zip](https://github.com/rollbar/Rollbar.NET/files/3872840/Rollbar.3.6.3.nupkg.zip)
Let me know if you need help with how to use Nuget-like local repo of packages with VS for Mac...

**Comment by azuken** [comment] 2019-11-21 08:31
Same error, `Method not found: string SQLitePCL.raw.sqlite3_db_filename(SQLitePCL.sqlite3,string)`

Here is more informations from `TargetSite`property : 

`{Void ConnectionOpening(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1[Microsoft.EntityFrameworkCore.DbLoggerCategory+Database+Connection], Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.DateTimeOffset, Boolean)}`

and the stacktrace : 

`  at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.ConnectionOpening (Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1[TLoggerCategory] diagnostics, Microsoft.EntityFrameworkCore.Storage.IRelationalConnection connection, System.DateTimeOffset startTime, System.Boolean async) [0x0002e] in <71d9d043aef04336aba3ddeb79c061d9>:0 
  at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open (System.Boolean errorsExpected) [0x00059] in <71d9d043aef04336aba3ddeb79c061d9>:0 
  at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open (System.Boolean errorsExpected) [0x00000] in <dcd9c338016142ef8d75315281f17c5f>:0 
  at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Exists () [0x0000c] in <dcd9c338016142ef8d75315281f17c5f>:0 
  at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated () [0x00000] in <71d9d043aef04336aba3ddeb79c061d9>:0 
  at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated () [0x00006] in <0998bf911f014e7884d2695c95a67016>:0 
  at Rollbar.PayloadStore.StoreContext.MakeSureDatabaseExistsAndReady () [0x00008] in <b15460250978400e90a248ef7b6fae0c>:0 
  at Rollbar.RollbarQueueController.Start () [0x0001a] in <b15460250978400e90a248ef7b6fae0c>:0 
  at Rollbar.RollbarQueueController..ctor () [0x0005d] in <b15460250978400e90a248ef7b6fae0c>:0 
  at Rollbar.RollbarQueueController+NestedSingleInstance..cctor () [0x00000] in <b15460250978400e90a248ef7b6fae0c>:0 `

**Comment by akornich** [comment] 2019-11-21 19:03
@azuken , thanks for trying it out. There is a similar problem reported here: https://github.com/fsprojects/Paket/issues/3632
and it looks like some recent MS EFCore SQLite and its SQLite provider library stack problem. I'll try suggested downgrade of the stack versions let's see how that plays out...

**Comment by akornich** [comment] 2019-11-22 03:14
@azuken , no luck for now with the latest experimentation. However, I did manage to repro a very similar problem that you are facing with a macOS/C# application using Rollbar.NET targeting NetStandard2.1 in VS for Mac. I also managed to fix that problem but got another one within EF Core model creation code that looks to me like a bug somewhere there in the Reflection based code. I already reported it to the EF Core team: https://github.com/aspnet/EntityFrameworkCore/issues/19024
Let's see what they reply...

**Comment by beeradmoore** [comment] 2019-12-03 21:05
Hey @akornich , I was just wondering if this exception was related to your above comment.

```
An exception was thrown when the constructor for type 'SomeProject.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException


   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
The type initializer for 'NestedSingleInstance' threw an exception.: TypeInitializationException
   at SomeProject.Startup.ConfigureRollbar() in /Users/SomeUser/git/SomeThing/SomeProject/SomeProject/src/SomeProject/Startup.cs:line 83
   at SomeProject.Startup.ConfigureServices(IServiceCollection services) in /Users/SomeUser/git/SomeThing/SomeProject/SomeProject/src/SomeProject/Startup.cs:line 99
   --- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
The type initializer for 'NestedSingleInstance' threw an exception.: TypeInitializationException
   at Rollbar.RollbarClient..ctor(IRollbarConfig rollbarConfig)
   at Rollbar.RollbarClient..ctor(RollbarLogger rollbarLogger)
   at Rollbar.RollbarLogger..ctor(Boolean isSingleton, IRollbarConfig rollbarConfig)
   at Rollbar.RollbarFactory.CreateNew(Boolean isSingleton)
   at Rollbar.RollbarLocator.NestedSingleInstance..cctor()
SQLite Error 14: 'unable to open database file'.: SqliteException
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at Rollbar.RollbarQueueController.Start()
   at Rollbar.RollbarQueueController.NestedSingleInstance..cctor()
```

This is an issue  when running in AWS Lambda (dotnet core 2.1) with Rollbar.NetCore.AspNet 3.6.3 and 3.6.2. 3.5 seems to work.

**Comment by akornich** [comment] 2019-12-04 00:33
Submitted as [a Xamarin issue](https://github.com/xamarin/xamarin-macios/issues/7541)

**Comment by beeradmoore** [comment] 2019-12-04 22:15
@akornich does that above exception look related to the EF/Xamarin issues you filed or should I file a new issue here?

**Comment by akornich** [comment] 2019-12-05 00:25
Hi @beeradmoore, the exception you posted here does not look related to this issue at all. This issue is very specific to Xamarin on iOS/macOS. Yours seems to be caused by failing access to the Rollbar SDK's db file.
Please, make sure nothing else holds exclusive access to the db file. You may also want to try setting a custom db location in the config (to a folder with enough RW credentials). If none of these fix the situation you may want to file a separate issue.
Good luck!

**Comment by akornich** [comment] 2019-12-05 00:42
Hi @azuken, I have a brief update on your issue:
the EF Core team does not recommend integrating Nuget packages via packages.config. They say it causes second-hand dependencies to not resolve properly. My [sample macOS app with VS for Mac](https://github.com/rollbar/Rollbar.NET/blob/master/Samples/Sample.Xamarin.MacApp.sln) seemed to have very similar exception until I moved it to use PackageReference for Rollbar.NET SDK instead of packages.config approach that seems to be applied by the VS for Mac by default. 
So, please, make sure all your relevant projects only reference the SDK like so:
```xml
<ItemGroup>
        <PackageReference Include="Rollbar" Version="3.6.3" />
    </ItemGroup>
```
and all the lagacy setting relying on packages.config are removed.

BTW, the Xamarin related issue referenced a few posts above was resolved by simply moving Rollbar SDK initialization code to a bit later location in the application initialization sequence (to after full Xamarin runtime initialization).

Best regards and good luck! Let me know how it went...

**Comment by beeradmoore** [comment] 2019-12-05 02:10
@akornich , ah k. Interesting. Was just by fluke both were related to EF and stuff. All good.
Setting LocalPayloadStoreLocationPath to /tmp/ (lambda writable path) didn't help. When I can make a smaller repro project I'll file a new issue.

Rolling back to 3.5.0 for now.

**Comment by akornich** [comment] 2019-12-05 22:27
@beeradmoore , sounds good!

**Comment by azuken** [comment] 2019-12-09 08:56
@akornich We already have this reference. In our Android csproj file, we have : 


```
    <PackageReference Include="Rollbar">
      <Version>3.6.3</Version>
    </PackageReference>
```

I verified if we had llegacy packages.config files, but I didn't find anything... So it must be something else.

**Comment by akornich** [comment] 2020-01-23 22:13
Hi @azuken , I just wanted to follow up on this issue. Are you still experiencing this problem? Did you have a chance to try v3.7.0?

**Comment by azuken** [comment] 2020-02-06 09:49
Sorry for the late response.

It seems to work fine now, I've tested build and launch for Android & iOS in Debug & Release mode.
But an exception still remains (Debug mode), and I don't know what to do with this :

```
split_config.xxhdpi.apk Error: 0 : Error while attempting to get RollbarTelemetryConfigSection:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
  at System.Configuration.ClientConfigPaths..ctor (System.String exePath, System.Boolean includeUserConfig) [0x00050] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigPaths.GetPaths (System.String exePath, System.Boolean includeUserConfig) [0x00018] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.get_ConfigPaths () [0x0000a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.GetStreamName (System.String configPath) [0x0006d] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.get_IsAppConfigHttp () [0x00000] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.Internal.DelegatingConfigHost.get_IsAppConfigHttp () [0x00006] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationSystem..ctor () [0x00051] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ConfigurationManager.EnsureConfigurationSystem () [0x00024] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
   --- End of inner exception stack trace ---
  at System.Configuration.ConfigurationManager.EnsureConfigurationSystem () [0x00060] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ConfigurationManager.PrepareConfigSystem () [0x0000a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ConfigurationManager.GetSection (System.String sectionName) [0x0000a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at Rollbar.NetFramework.RollbarTelemetryConfigSection.GetConfiguration () [0x00000] in <e7c62467a6e0493c93022f22cddd472f>:0 
split_config.xxhdpi.apk Error: 0 : Error while attempting to get RollbarConfigSection:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
  at System.Configuration.ClientConfigPaths..ctor (System.String exePath, System.Boolean includeUserConfig) [0x00050] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigPaths.GetPaths (System.String exePath, System.Boolean includeUserConfig) [0x00018] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.get_ConfigPaths () [0x0000a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.GetStreamName (System.String configPath) [0x0006d] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationHost.get_IsAppConfigHttp () [0x00000] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.Internal.DelegatingConfigHost.get_IsAppConfigHttp () [0x00006] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ClientConfigurationSystem..ctor () [0x00051] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ConfigurationManager.EnsureConfigurationSystem () [0x00024] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
   --- End of inner exception stack trace ---
  at System.Configuration.ConfigurationManager.PrepareConfigSystem () [0x0001a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at System.Configuration.ConfigurationManager.GetSection (System.String sectionName) [0x0000a] in <5ae095f7408b4d5cb5cdbfc3d3c31d20>:0 
  at Rollbar.NetFramework.RollbarConfigSection.GetConfiguration () [0x00000] in <e7c62467a6e0493c93022f22cddd472f>:0 
```

Have you any idea ? Maybe I'm missing something in initialization.

**Comment by akornich** [comment] 2020-02-08 00:19
@azuken , it seems like the initialization process is trying to read in XML config sections for Rollbar and Rollbar telemetry and some APIs used by `System.Configuration.ConfigurationManager` are not available on the OS platform(s). I think, now I have enough data to pinpoint the cause and find a fix. Thanks!
You said it happens on both iOS and Android in Debug mode?

**Comment by akornich** [comment] 2020-02-08 00:35
@azuken , these are not unhandled exceptions but reports in the trace output. Correct?
I bet they are. Here is where they are coming from:
```
        public static RollbarConfigSection GetConfiguration()
        {
            try
            {
                RollbarConfigSection configuration =
                    ConfigurationManager.GetSection("rollbar")
                    as RollbarConfigSection;
                return configuration;
            }
            catch (Exception ex)
            {
                //let's just trace it for now:
                Trace.TraceError(
                    "Error while attempting to get RollbarConfigSection:" + System.Environment.NewLine + ex
                    );
                return null;
            }
        }

We already guard use of the configuration manager and if anything goes wrong (like a specific OS does not support part of its functionality in this case) we just trace the exception.
It is not an unhandled exception and by no means a critical error. Think of it this way: we are trying to automate some of the SDK initialization steps whenever possible so that the client code does not have to explicitly load the SDK config from the config files in code (what if the user already placed one of the supported config files and we try to evaluate ourselves but expect to fail if the assumption is wrong).
Does it make sense now?

**Comment by azuken** [comment] 2020-02-10 09:33
Ok it's more clear now ! So I can let it appears in the console, if I'm correct I cannot hide it ?

**Comment by akornich** [comment] 2020-02-10 20:50
yes, you can safely ignore it. as far as hiding it, currently, I do not know about any way of doing it on your side. However, we can change the error reporting via trace source instead of trace, so then you will not see the trace message unless you explicitly subscribe a listener to the trace source.

**Comment by azuken** [comment] 2020-02-11 08:50
It would be great :) Thank you anyway for your support and your reactivity !

**Comment by akornich** [comment] 2020-05-07 21:14
closing. resolving #502 took care of this one.

**Closed by akornich** 2020-05-07 21:14 UTC
Labels: bug, dependencies
