### ISSUE TITLE
[DOCS] Azure Functions Dependencies

### ISSUE THREAD

**Issue by ajtran** [rollbar/Rollbar.NET#90] opened 2018-02-27 21:18 UTC
User received this error:

`The type initializer for 'Rollbar.DTOs.ExtendableDtoBase' threw an exception. ---> System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.`

Solution:

Rollbar and Microsoft.NET.Sdk.Function are fighting over what version of Newtonsoft.Json to run. If you set this explicitly to 10.0.3 in your project file, it will run.

```
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.8" /> 
<PackageReference Include="Newtonsoft.Json" Version="10.0.3" /> 
<PackageReference Include="Rollbar" Version="1.0.3" />
```

The Microsoft.NET.Sdk.Functions package currently has a hard dependency on Newtonsoft.Json 9.0.1, and Rollbar needs 10.0.3 and doesn't seem to like 11.0.1

Upgrading docs to reflect this would be helpful for other users who encounter the same error.

Internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813342/conversations/14895699833

**Comment by akornich** [comment] 2018-02-27 23:19
this one could be taken care once fix for [](https://github.com/rollbar/Rollbar.NET/issues/91) is applied.

**Comment by akornich** [comment] 2018-03-14 19:01
Rollbar.NET v1.1.0 is out and this issue should be addressed by the release indirectly as well. Please, verify and close the issue if the issue is taken care of.

**Comment by ajtran** [comment] 2018-04-06 00:35
@akornich the user has been contacted.

**Comment by akornich** [comment] 2018-04-10 17:36
@ajtran, do we have any feedback from the user?

**Comment by ajtran** [comment] 2018-04-10 17:39
@akornich I do not.

**Comment by jessewgibbs** [comment] 2018-04-13 19:35
@akornich any reason to believe that this issue not fixed by https://github.com/rollbar/Rollbar.NET/issues/91?  The user is probably non-responsive because the issue has gone away...

If we no longer have the dependency issue, then there's no need for docs.

**Comment by akornich** [comment] 2018-04-13 20:38
@ajtran, can we ping the user if this is still an issue for them?

**Comment by akornich** [comment] 2018-04-14 00:12
@jessewgibbs , yes, 1.2.0 has it all. my fork has only changes resolving #118

**Comment by jessewgibbs** [comment] 2018-04-16 15:40
I'm going to notify the customer and close this issue.

**Comment by lorddev** [comment] 2018-09-25 16:16
I'm getting this issue in Azure Functions with Rollbar 1.5.6.

**Comment by akornich** [comment] 2018-09-25 17:27
@lorddev, thanks for reporting the issue. 
what versions exactly are in conflict? 
if you could post repro steps that would be really helpful.

**Comment by jessewgibbs** [comment] 2018-10-19 16:09
I'm going to close this issue since the last person to report it didn't follow up with additional info.

**Closed by jessewgibbs** 2018-10-19 16:09 UTC

**Comment by lorddev** [comment] 2019-03-01 23:02
I'm using the latest version and no longer getting these errors.

**Comment by akornich** [comment] 2019-03-01 23:25
@lorddev , nice! thanks for the update!
