### ISSUE TITLE
Using Rollbar.NET in an Azure Function throws SQLite Error 14: 'unable to open database file'

### ISSUE THREAD

**Issue by stay2be** [rollbar/Rollbar.NET#485] opened 2019-12-09 16:36 UTC
**Describe the bug**
Using the Rollbar.NET lib in an Azure Function for tracking errors results in the following error: SQLite Error 14: 'unable to open database file'.

This is because the function is run inside a Zip file (read only mode, default behavior when you create a function).

**To Reproduce**
1. Creating an Azure Function (Linux or WIndows)
2. Include and configure the latest Rollbar.NET nuget pakage
3. Deploy a test function with e. g. Azure Dev Ops
4. Let the config value "WEBSITE_RUN_FROM_PACKAGE" to it's default value (1)
5. Running the function produces the error above.

**Expected behavior**
An option to disable writing to a local file (SQLite database) in the config. There are maybe more environments where this could be needed. For example: newly created Azure Web Apps for Windows are configured that the app running inside has readonly rights to the file system.

Please either provide a config option for disabling sql store or document this limitation in the docs (or readme).

**Rollbar Client - Rollbar.NET Hosting Environment:**
 - Rollbar.NET Host type: Azure Function (Linux)
 - OS and its version: Linux
 - .NET flavor and its version: .NET Core 2.x
 - Application framework and its version: Azure FUnction SDK
 - Rollbar.NET Version: 3.6.3
 - Applicable Rollbar Plug-in (if any): none
 - Applicable custom third party logging library/framework integration (if any): Azure Function SDK logging (but not related to Rollbar)
 - Applicable Browser (if any): n/a

**Comment by akornich** [comment] 2019-12-09 22:30
#486

**Comment by beeradmoore** [comment] 2019-12-13 01:24
@stay2be was this the full error it triggered?

```
An exception was thrown when the constructor for type 'SomeProject.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException


   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
The type initializer for 'NestedSingleInstance' threw an exception.: TypeInitializationException
   at SomeProject.Startup.ConfigureRollbar() in /Users/SomeUser/git/SomeThing/SomeProject/SomeProject/src/SomeProject/Startup.cs:line 83
   at SomeProject.Startup.ConfigureServices(IServiceCollection services) in /Users/SomeUser/git/SomeThing/SomeProject/SomeProject/src/SomeProject/Startup.cs:line 99
   --- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
The type initializer for 'NestedSingleInstance' threw an exception.: TypeInitializationException
   at Rollbar.RollbarClient..ctor(IRollbarConfig rollbarConfig)
   at Rollbar.RollbarClient..ctor(RollbarLogger rollbarLogger)
   at Rollbar.RollbarLogger..ctor(Boolean isSingleton, IRollbarConfig rollbarConfig)
   at Rollbar.RollbarFactory.CreateNew(Boolean isSingleton)
   at Rollbar.RollbarLocator.NestedSingleInstance..cctor()
SQLite Error 14: 'unable to open database file'.: SqliteException
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at Rollbar.RollbarQueueController.Start()
   at Rollbar.RollbarQueueController.NestedSingleInstance..cctor()
```

I have a similar issue with AWS Lambda (but have not had time to reproduce it in a smaller project yet) when using > Rollbar.NET 3.5. I mentioned it elsewhere but the issue was not related. I haven't had time to reproduce it in a smaller project yet. The [suggested solution](https://github.com/rollbar/Rollbar.NET/issues/475#issuecomment-561908721) for me was to move the file into a writeable folder. But moving it to /tmp/ (the RW folder for AWS Lambda) it still gave the same error. 

If it is the same error, does setting `LocalPayloadStoreLocationPath` to a RW path on your `RollbarConfig` fix it?

Although above, #486 should fix the issue (and in general probably be preferable for Azure/Lambda calls) by not creating the persistent storage.

**Comment by beeradmoore** [comment] 2019-12-13 03:41
I managed to reproduce it: [RollbarDotNETTest.zip](https://github.com/rollbar/Rollbar.NET/files/3958914/RollbarDotNETTest.zip)

This is the output of the TraceAsString()
```
RollbarConfig:
  AccessToken: POST_SERVER_ITEM_ACCESS_TOKEN
  EndPoint: https://api.rollbar.com/api/1/
  ScrubFields: System.String[]
  ScrubWhitelistFields: System.String[]
  Enabled: True
  Environment: production
  Server: 
  Person: 
  ProxyAddress: 
  MaxReportsPerMinute: 
  ReportingQueueDepth: 20
  MaxItems: 0
  CaptureUncaughtExceptions: True
  IpAddressCollectionPolicy: Collect
  PersonDataCollectionPolicies: None
  StoreDb: /tmp/RollbarPayloadsStore.db
```

Followed by this exception:
```
The type initializer for 'NestedSingleInstance' threw an exception.: TypeInitializationException
   at RollbarDotNETTest.Function.FunctionHandler(Input input, ILambdaContext context) in /Users/bradmoore/Desktop/RollbarTest/RollbarDotNETTest/src/RollbarDotNETTest/Function.cs:line 29
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at Rollbar.RollbarClient..ctor(IRollbarConfig rollbarConfig)
   at Rollbar.RollbarClient..ctor(RollbarLogger rollbarLogger)
   at Rollbar.RollbarLogger..ctor(Boolean isSingleton, IRollbarConfig rollbarConfig)
   at Rollbar.RollbarFactory.CreateNew(Boolean isSingleton)
   at Rollbar.RollbarLocator.NestedSingleInstance..cctor()
SQLite Error 14: 'unable to open database file'.: SqliteException
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Rollbar.RollbarQueueController.Start()
   at Rollbar.RollbarQueueController.NestedSingleInstance..cctor()
```

**Comment by akornich** [comment] 2019-12-13 04:21
@beeradmoore , thanks for the repro! I'll look into it tomorrow morning. For now, a brief correction: in the config, the `StoreDb: /tmp/RollbarPayloadsStore.db`needs to be replaced with `LocalPayloadStoreLocationPath: /tmp`.

**Comment by beeradmoore** [comment] 2019-12-13 04:41
I'm setting the LocalPayloadStoreLocationPath with 
```
config.LocalPayloadStoreLocationPath = Path.GetTempPath();
```
before these lines are called
```
context?.Logger?.Log(config.TraceAsString());
RollbarLocator.RollbarInstance.Configure(config);
```

`StoreDb` looks to be the combination of LocalPayloadStoreLocationPath and LocalPayloadStoreFileName. 

/tmp/ is the correct path for Lambda R/W, its odd this thing is giving this error.  I added 
```
try
{
    var testFile = Path.Combine(config.LocalPayloadStoreLocationPath, "somefile.txt");
    System.IO.File.WriteAllText(testFile, "some text");
    var fileInfo = new FileInfo(testFile);
    context?.Logger?.Log($"FileSize: {fileInfo.Length} bytes");

}
catch (Exception err)
{
    context?.Logger?.Log($"ERROR: {err.Message}");
}
```

Between the `context?.Logger?.Log(config.TraceAsString());` and `RollbarLocator.RollbarInstance.Configure(config);`.  It outputs `FileSize: 9 bytes` which is expected. So IO to that directory is working.

**Comment by kieranbenton** [comment] 2019-12-16 14:40
Just to add my 2cents - I am experiencing exactly the same as you @beeradmoore - but running an application in a docker container, with the application not running as root and not having access to its own directory to create/modify files.

I too configure as:
```
	var config = new RollbarConfig(accesstoken)
	{
		Environment = hostEnvironment.EnvironmentName,
		LocalPayloadStoreLocationPath = Path.GetTempPath()
	};

	RollbarLocator.RollbarInstance.Configure(config);
```

This is at the earliest opportunity, and before any other calls to the SDK, but have managed to confirm using ```strace -e trace=file <app>``` that the Rollbar SDK is still trying to write the database files to the current directory before the setting takes effect.

```    
     openat(AT_FDCWD, "/app/RollbarPayloadsStore.db", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = -1 EACCES (Permission denied)
     openat(AT_FDCWD, "/app/RollbarPayloadsStore.db-wal", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = -1 EACCES (Permission denied)
```

I've confirmed this by running as root, and the ```RollbarPayloadsStore.db``` file appears in both the current directory AND /tmp/.

So it looks as if the setting is taking effect, but AFTER initialisation which is too late when running an application in a constrained environment.

Let me know if you need any more information.

**Comment by kieranbenton** [comment] 2019-12-16 14:40
I'm going to try the suggestion to use appsettings now.

**Comment by akornich** [comment] 2019-12-16 20:24
@kieranbenton , @beeradmoore , thanks for the very useful input!
I'll try to make the payload persistence optional and make a release by the end of this week.
I am also thinking about making explicit initialization/start-up of the internal payload queues processor, so that you, guys, can do something like RollbarQueueController.Instance.Configure(...).Start() or RollbarQueueController.Instance.Start(configuration).
Any alternative suggestions?

**Comment by kieranbenton** [comment] 2019-12-17 11:53
That makes sense @akornich. 

Ideally I'd like Rollbar.NET to work with the .NET Core dependency injection system - so not have to use a static singleton, and instead inject an ```IRollbar``` into every class that requires it. Configuring it would then be done in Statup.cs via the usual ```.AddXXX``` pattern, adding it as a singleton.

But I'm guessing maintaining backwards compatibility is an obvious concern for you so understand why you wouldn't want to make that dramatic a change now.

**Comment by akornich** [comment] 2019-12-17 22:50
@kieranbenton , did you try using our Rollbar.NetCore.AspNet adapter? It has AspNetCore Rollbar middleware and logger implemented.

**Comment by kieranbenton** [comment] 2019-12-18 18:03
@akornich thanks for the heads up - didn't realise that was a thing! I'm going to assume this bug is going to affect that though in the same way? In which case I'll just wait for you to release for now - and maybe switch to that in the future.

**Comment by akornich** [comment] 2019-12-18 18:12
@kieranbenton, btw, you can use any Rollbar component of v3.5.0 or older without running into this issue. The payload persistence was added past v3.5.0.

**Comment by akornich** [comment] 2019-12-24 17:46
#486 and release v3.7.0 should already address this issue

**Comment by beeradmoore** [comment] 2020-01-07 04:52
Confirming that adding 

```
rollbarConfig.EnableLocalPayloadStore = false;
```

in v3.7.0 fixed the issue for me.

**Comment by akornich** [comment] 2020-01-07 04:57
@beeradmoore , thanks for the confirmation!

**Comment by webcoyote** [comment] 2020-01-09 05:49
I'm having the same issue as kieranbenton: setting `rollbarConfig.LocalPayloadStoreLocationPath = Path.GetTempPath()` leads to two files being created: one in the current working directory, and one in the temp directory. This is inconvenient in development, but in production the application cannot write to the local directory.

Like kieranbenton I also need this to work on Windows/OSX/Linux, and so cannot easily support multiple configuration files for each platform. I can disable the LocalPayloadStore, as suggested by beeradmoore, but then crashes won't get reported to the server.

Is there an ETA for the next version that will correct this issue, so that the LocalPayloadStore file will only be created in the correct location?

Thanks!

**Comment by kieranbenton** [comment] 2020-01-09 17:40
@webcoyote have you tried the v3.7.0 release @akornich mentions above? I've not had chance to upgrade and try it myself yet.

**Comment by webcoyote** [comment] 2020-01-09 17:50
@kieranbenton -- I misunderstood the dialog between akornich and beeradmoore, and thought that 3.7.0 allowed disabling the feature. I upgraded to 3.7.0 and that does correct the problem; thanks!

**Comment by akornich** [comment] 2020-01-09 20:39
@webcoyote, thanks for the confirmation. I am glad you are unblocked now. I guess it is time for me to take a look at the static initialization sequence and clean it up.
@webcoyote, @kieranbenton, @beeradmoore -  also, I was thinking about splitting the current RollbarConfig into two parts (independent config objects/types): one config for specifically configuring a RollbarLogger instance(s) and another part for configuring the "background engine" singleton (ie RollbarQueueController) behavior.  All comments, suggestions, ideas are welcome...

**Comment by beeradmoore** [comment] 2020-01-15 22:32
@akornich , with 3.7.0 if I have EnableLocalPayloadStore enabled and I do attempt to use payload store I'll get the original error again.  

```
rollbarConfig.EnableLocalPayloadStore = true;
rollbarConfig.LocalPayloadStoreLocationPath = Path.GetTempPath();
```

As @kieranbenton said, setting it in code doesn't work (I assume this was 3.5.0), but confirming setting it in code in 3.7.0 still doesn't work.

**Comment by akornich** [comment] 2020-01-16 00:48
@beeradmoore , yes, i'll have to look into the initialization sequence issue with custom db path - it does not happen as designed. i'll probably be looking into it next week.
for now, i just want to clarify that you can run everything successfully when having the persistence off, i.e.: 
`rollbarConfig.EnableLocalPayloadStore = false;`

**Comment by beeradmoore** [comment] 2020-01-16 01:02
My code executes and I am able to log errors when I have `rollbarConfig.EnableLocalPayloadStore = false;`. 

If I just do a 
```
throw new Exception($"some exception - {DateTime.Now}");
```

I get an error that says
```
[Error] Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction: Unknown error responding to request: RollbarMiddlewareException:
Rollbar.NetCore.AspNet.RollbarMiddlewareException: The included internal exception processed by the Rollbar middleware ---> System.Exception: some exception - 1/16/20 12:55:28 AM
```

I don't know if that is related or if catching exceptions just never worked for me in the first place.

**Comment by akornich** [comment] 2020-01-16 01:21
@beeradmoore ,  the `Rollbar.NetCore.AspNet.RollbarMiddlewareException` is intended to communicate cases when the Rollbar middleware is hooked up into the Asp.Net Core middleware chain and it sees an unhandled exception (referred to as "The included internal exception") in the middleware chain following the RollbarMiddleware (i.e. "guarded" by RollbarMiddleware). 
BTW, do you see this RollbarMiddlewareException also reported to the Rollbar dashboard? If yes, it works as intended.

**Comment by akornich** [comment] 2020-01-16 02:05
@beeradmoore , when encountering any odd behavior of the SDK, try subscribing to its [internal events](https://docs.rollbar.com/docs/dotnet#section-monitoring-the-notifiers-internal-events). Often they provide the "missing details" about what's going on...

**Comment by akornich** [comment] 2020-02-10 22:41
is this one still an issue or we can close it?

**Closed** 2020-09-11 19:16 UTC
Labels: bug
